Add talks for the winter semester 2017/2018
hfuunfug/unfug.org pull request #99
Opened 2017-10-06 09:42 UTC by neithernut

Please give some feedback:
@asuivelentine
@manuelmessner
@Senkor

2017-10-06 10:39 UTC, matthiasbeyer requested changes
Wow, all dates are taken! Looks awesome, I'd love to attend some dates.

2017-10-06 10:39 UTC, matthiasbeyer commented on content/talks/2017-12-14-PEARL.md
> +title: Fuwa News Show
Copy-Paste fail.

2017-10-06 10:39 UTC, matthiasbeyer commented on content/talks/2017-12-21-Challenge.md
> +title: Fuwa News Show
Copy-Paste fail.

2017-10-06 10:54 UTC, asuivelentine commented
with the changes mentioned by @matthiasbeyer this looks good for me.

2017-10-09 07:43 UTC, neithernut commented
Any other suggestions? Could someone merge this, please?

2017-10-09 11:19 UTC, matthiasbeyer commented
IMO ack.

2017-10-09 11:20 UTC, merged